[package]
name = "i8080"
version = "0.1.0"
authors = ["Aaron Power <theaaronepower@gmail.com>"]

[dependencies]
clap = "2.26"
ears = "0.4"
image = { version = "0.15", default-features = false }
piston_window = "0.70"

[features]
cpudiag = []
